services:
  web:
    build: .
    container_name: web
    entrypoint: ./entrypoint.sh
    env_file:
      - ./app/.env
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app
  db:
    image: postgres:alpine
    container_name: db
    env_file:
      - ./app/.env
    volumes:
     - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
